#!/bin/sh

PYTHON_FRAMEWORKS="pythonsupport" # Python frameworks


source "$PYTHON_FRAMEWORKS".sh # Load functions Python frameworks

common_commands() {
    check_python_version
        if [[ "$2" == "start" ]]; then
            echo "Starting $1"
            start_$framework
        elif [[ "$2" == "startproject" ]]; then
            startproject_$framework $3 $4
        elif [[ "$2" == "run" ]]; then
            run_$framework
        elif [[ "$2" == "stop" ]]; then
            stop_$framework
        fi
}

# set a variable to the value of the first argument
framework=""
case "$1" in 
    -d|--django)
        framework="django"
        common_commands $framework $2 $3 $4
        ;;
    -f|--flask)
        framework="flask"
        common_commands $framework $2 $3 $4
        ;;
    -fs|--fastapi)
        framework="fastapi"
        common_commands $framework $2 $3 $4
    -h|--help)
        # print header as enginx
echo " _________                                          __       __
|   ______|                         __             \  \    /  /
|  |                               |__|             \  \  /  /
|  |____     __ ____      _____     __   __ ____     \  \/  /
|   ____|   |  |__  \   /  ___  \  |  | |  |__  \     |    |
|  |        |  |  |  | |  |   |  | |  | |  |  |  |   /  /\  \ 
|  |______  |  |  |  | |  |___|  | |  | |  |  |  |  /  /  \  \ 
|_________| |__|  |__|  \ ____   | |__| |__|  |__| /__/    \__\ 
                          ____|  |  
                         |_____ /
"
        e_header "CLI Tool for creating and setting up your projects"
        e_shameless_plug "Authored by: Swarup Kharul (https://github.com/SwarupKharul)"
        echo "Usage:"
        echo "  $0 [option] <command> <arg1> <arg2>"
        echo "  $0 --django startproject <project_name> <app_name>"
        echo "   "
        echo "Options:"
        echo "  -d, --django    For Django framework" 
        echo "  -f, --flask     For Flask framework"
        echo "  -h, --help      Show this screen"
        ;;
esac